# make an easy calculator using python.
test1 = input("Type Your Number Here Please: ")
test2 = input("Type Your Other Number Here Please: ")
result1 = int(test1)
result2 = int(test2)
print("addition")
print(result1 + result2)
print("Multiplication")
print(result1 * result2)
print("Divided by")
print(result1 % result2)
print("Subtraction")
print(result1 - result2)
